// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: client/v1/callback.proto

package clientv1

import (
	v1 "github.com/JrMarcco/kuryr-api/api/go/notification/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendResultNotifyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId uint64                 `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	RawRequest     *v1.SendRequest        `protobuf:"bytes,2,opt,name=raw_request,json=rawRequest,proto3" json:"raw_request,omitempty"`
	Result         *v1.SendResult         `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendResultNotifyRequest) Reset() {
	*x = SendResultNotifyRequest{}
	mi := &file_client_v1_callback_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResultNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResultNotifyRequest) ProtoMessage() {}

func (x *SendResultNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_callback_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResultNotifyRequest.ProtoReflect.Descriptor instead.
func (*SendResultNotifyRequest) Descriptor() ([]byte, []int) {
	return file_client_v1_callback_proto_rawDescGZIP(), []int{0}
}

func (x *SendResultNotifyRequest) GetNotificationId() uint64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

func (x *SendResultNotifyRequest) GetRawRequest() *v1.SendRequest {
	if x != nil {
		return x.RawRequest
	}
	return nil
}

func (x *SendResultNotifyRequest) GetResult() *v1.SendResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type SendResultNotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResultNotifyResponse) Reset() {
	*x = SendResultNotifyResponse{}
	mi := &file_client_v1_callback_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResultNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResultNotifyResponse) ProtoMessage() {}

func (x *SendResultNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_v1_callback_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResultNotifyResponse.ProtoReflect.Descriptor instead.
func (*SendResultNotifyResponse) Descriptor() ([]byte, []int) {
	return file_client_v1_callback_proto_rawDescGZIP(), []int{1}
}

func (x *SendResultNotifyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_client_v1_callback_proto protoreflect.FileDescriptor

const file_client_v1_callback_proto_rawDesc = "" +
	"\n" +
	"\x18client/v1/callback.proto\x12\tclient.v1\x1a\"notification/v1/notification.proto\"\xb6\x01\n" +
	"\x17SendResultNotifyRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x04R\x0enotificationId\x12=\n" +
	"\vraw_request\x18\x02 \x01(\v2\x1c.notification.v1.SendRequestR\n" +
	"rawRequest\x123\n" +
	"\x06result\x18\x03 \x01(\v2\x1b.notification.v1.SendResultR\x06result\"4\n" +
	"\x18SendResultNotifyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2n\n" +
	"\x0fCallbackService\x12[\n" +
	"\x10SendResultNotify\x12\".client.v1.SendResultNotifyRequest\x1a#.client.v1.SendResultNotifyResponseB\x9c\x01\n" +
	"\rcom.client.v1B\rCallbackProtoP\x01Z7github.com/JrMarcco/kuryr-api/api/go/client/v1;clientv1\xa2\x02\x03CXX\xaa\x02\tClient.V1\xca\x02\tClient\\V1\xe2\x02\x15Client\\V1\\GPBMetadata\xea\x02\n" +
	"Client::V1b\x06proto3"

var (
	file_client_v1_callback_proto_rawDescOnce sync.Once
	file_client_v1_callback_proto_rawDescData []byte
)

func file_client_v1_callback_proto_rawDescGZIP() []byte {
	file_client_v1_callback_proto_rawDescOnce.Do(func() {
		file_client_v1_callback_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_v1_callback_proto_rawDesc), len(file_client_v1_callback_proto_rawDesc)))
	})
	return file_client_v1_callback_proto_rawDescData
}

var file_client_v1_callback_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_client_v1_callback_proto_goTypes = []any{
	(*SendResultNotifyRequest)(nil),  // 0: client.v1.SendResultNotifyRequest
	(*SendResultNotifyResponse)(nil), // 1: client.v1.SendResultNotifyResponse
	(*v1.SendRequest)(nil),           // 2: notification.v1.SendRequest
	(*v1.SendResult)(nil),            // 3: notification.v1.SendResult
}
var file_client_v1_callback_proto_depIdxs = []int32{
	2, // 0: client.v1.SendResultNotifyRequest.raw_request:type_name -> notification.v1.SendRequest
	3, // 1: client.v1.SendResultNotifyRequest.result:type_name -> notification.v1.SendResult
	0, // 2: client.v1.CallbackService.SendResultNotify:input_type -> client.v1.SendResultNotifyRequest
	1, // 3: client.v1.CallbackService.SendResultNotify:output_type -> client.v1.SendResultNotifyResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_client_v1_callback_proto_init() }
func file_client_v1_callback_proto_init() {
	if File_client_v1_callback_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_v1_callback_proto_rawDesc), len(file_client_v1_callback_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_v1_callback_proto_goTypes,
		DependencyIndexes: file_client_v1_callback_proto_depIdxs,
		MessageInfos:      file_client_v1_callback_proto_msgTypes,
	}.Build()
	File_client_v1_callback_proto = out.File
	file_client_v1_callback_proto_goTypes = nil
	file_client_v1_callback_proto_depIdxs = nil
}
