// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: provider/v1/provider.proto

package providerv1

import (
	v1 "github.com/JrMarcco/kuryr-api/api/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Provider struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProviderName     string                 `protobuf:"bytes,2,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	Channel          v1.Channel             `protobuf:"varint,3,opt,name=channel,proto3,enum=common.v1.Channel" json:"channel,omitempty"`
	Endpoint         string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	RegionId         string                 `protobuf:"bytes,5,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	AppId            string                 `protobuf:"bytes,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ApiKey           string                 `protobuf:"bytes,7,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	ApiSecret        string                 `protobuf:"bytes,8,opt,name=api_secret,json=apiSecret,proto3" json:"api_secret,omitempty"`
	Weight           int32                  `protobuf:"varint,9,opt,name=weight,proto3" json:"weight,omitempty"`
	QpsLimit         int32                  `protobuf:"varint,10,opt,name=qps_limit,json=qpsLimit,proto3" json:"qps_limit,omitempty"`
	DailyLimit       int32                  `protobuf:"varint,11,opt,name=daily_limit,json=dailyLimit,proto3" json:"daily_limit,omitempty"`
	AuditCallbackUrl string                 `protobuf:"bytes,12,opt,name=audit_callback_url,json=auditCallbackUrl,proto3" json:"audit_callback_url,omitempty"`
	ActiveStatus     string                 `protobuf:"bytes,13,opt,name=active_status,json=activeStatus,proto3" json:"active_status,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *Provider) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Provider) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *Provider) GetChannel() v1.Channel {
	if x != nil {
		return x.Channel
	}
	return v1.Channel(0)
}

func (x *Provider) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Provider) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *Provider) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Provider) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *Provider) GetApiSecret() string {
	if x != nil {
		return x.ApiSecret
	}
	return ""
}

func (x *Provider) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Provider) GetQpsLimit() int32 {
	if x != nil {
		return x.QpsLimit
	}
	return 0
}

func (x *Provider) GetDailyLimit() int32 {
	if x != nil {
		return x.DailyLimit
	}
	return 0
}

func (x *Provider) GetAuditCallbackUrl() string {
	if x != nil {
		return x.AuditCallbackUrl
	}
	return ""
}

func (x *Provider) GetActiveStatus() string {
	if x != nil {
		return x.ActiveStatus
	}
	return ""
}

type SaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *SaveRequest) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *SaveResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{4}
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	Provider      *Provider              `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *UpdateRequest) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{6}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *ListRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *ListResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

type FindByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdRequest) Reset() {
	*x = FindByIdRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdRequest) ProtoMessage() {}

func (x *FindByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdRequest.ProtoReflect.Descriptor instead.
func (*FindByIdRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *FindByIdRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *FindByIdRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      *Provider              `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdResponse) Reset() {
	*x = FindByIdResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdResponse) ProtoMessage() {}

func (x *FindByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdResponse.ProtoReflect.Descriptor instead.
func (*FindByIdResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *FindByIdResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

type FindByChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	Channel       v1.Channel             `protobuf:"varint,2,opt,name=channel,proto3,enum=common.v1.Channel" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByChannelRequest) Reset() {
	*x = FindByChannelRequest{}
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByChannelRequest) ProtoMessage() {}

func (x *FindByChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByChannelRequest.ProtoReflect.Descriptor instead.
func (*FindByChannelRequest) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{11}
}

func (x *FindByChannelRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *FindByChannelRequest) GetChannel() v1.Channel {
	if x != nil {
		return x.Channel
	}
	return v1.Channel(0)
}

type FindByChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*Provider            `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByChannelResponse) Reset() {
	*x = FindByChannelResponse{}
	mi := &file_provider_v1_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByChannelResponse) ProtoMessage() {}

func (x *FindByChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_provider_v1_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByChannelResponse.ProtoReflect.Descriptor instead.
func (*FindByChannelResponse) Descriptor() ([]byte, []int) {
	return file_provider_v1_provider_proto_rawDescGZIP(), []int{12}
}

func (x *FindByChannelResponse) GetProviders() []*Provider {
	if x != nil {
		return x.Providers
	}
	return nil
}

var File_provider_v1_provider_proto protoreflect.FileDescriptor

const file_provider_v1_provider_proto_rawDesc = "" +
	"\n" +
	"\x1aprovider/v1/provider.proto\x12\vprovider.v1\x1a\x15common/v1/types.proto\x1a google/protobuf/field_mask.proto\"\x9e\x03\n" +
	"\bProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12#\n" +
	"\rprovider_name\x18\x02 \x01(\tR\fproviderName\x12,\n" +
	"\achannel\x18\x03 \x01(\x0e2\x12.common.v1.ChannelR\achannel\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x1b\n" +
	"\tregion_id\x18\x05 \x01(\tR\bregionId\x12\x15\n" +
	"\x06app_id\x18\x06 \x01(\tR\x05appId\x12\x17\n" +
	"\aapi_key\x18\a \x01(\tR\x06apiKey\x12\x1d\n" +
	"\n" +
	"api_secret\x18\b \x01(\tR\tapiSecret\x12\x16\n" +
	"\x06weight\x18\t \x01(\x05R\x06weight\x12\x1b\n" +
	"\tqps_limit\x18\n" +
	" \x01(\x05R\bqpsLimit\x12\x1f\n" +
	"\vdaily_limit\x18\v \x01(\x05R\n" +
	"dailyLimit\x12,\n" +
	"\x12audit_callback_url\x18\f \x01(\tR\x10auditCallbackUrl\x12#\n" +
	"\ractive_status\x18\r \x01(\tR\factiveStatus\"@\n" +
	"\vSaveRequest\x121\n" +
	"\bprovider\x18\x01 \x01(\v2\x15.provider.v1.ProviderR\bprovider\"A\n" +
	"\fSaveResponse\x121\n" +
	"\bprovider\x18\x01 \x01(\v2\x15.provider.v1.ProviderR\bprovider\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x10\n" +
	"\x0eDeleteResponse\"}\n" +
	"\rUpdateRequest\x129\n" +
	"\n" +
	"field_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x121\n" +
	"\bprovider\x18\x02 \x01(\v2\x15.provider.v1.ProviderR\bprovider\"\x10\n" +
	"\x0eUpdateResponse\"H\n" +
	"\vListRequest\x129\n" +
	"\n" +
	"field_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\"C\n" +
	"\fListResponse\x123\n" +
	"\tproviders\x18\x01 \x03(\v2\x15.provider.v1.ProviderR\tproviders\"\\\n" +
	"\x0fFindByIdRequest\x129\n" +
	"\n" +
	"field_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\"E\n" +
	"\x10FindByIdResponse\x121\n" +
	"\bprovider\x18\x01 \x01(\v2\x15.provider.v1.ProviderR\bprovider\"\x7f\n" +
	"\x14FindByChannelRequest\x129\n" +
	"\n" +
	"field_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x12,\n" +
	"\achannel\x18\x02 \x01(\x0e2\x12.common.v1.ChannelR\achannel\"L\n" +
	"\x15FindByChannelResponse\x123\n" +
	"\tproviders\x18\x01 \x03(\v2\x15.provider.v1.ProviderR\tproviders2\xb2\x03\n" +
	"\x0fProviderService\x12;\n" +
	"\x04Save\x12\x18.provider.v1.SaveRequest\x1a\x19.provider.v1.SaveResponse\x12A\n" +
	"\x06Delete\x12\x1a.provider.v1.DeleteRequest\x1a\x1b.provider.v1.DeleteResponse\x12A\n" +
	"\x06Update\x12\x1a.provider.v1.UpdateRequest\x1a\x1b.provider.v1.UpdateResponse\x12;\n" +
	"\x04List\x12\x18.provider.v1.ListRequest\x1a\x19.provider.v1.ListResponse\x12G\n" +
	"\bFindById\x12\x1c.provider.v1.FindByIdRequest\x1a\x1d.provider.v1.FindByIdResponse\x12V\n" +
	"\rFindByChannel\x12!.provider.v1.FindByChannelRequest\x1a\".provider.v1.FindByChannelResponseB\xaa\x01\n" +
	"\x0fcom.provider.v1B\rProviderProtoP\x01Z;github.com/JrMarcco/kuryr-api/api/go/provider/v1;providerv1\xa2\x02\x03PXX\xaa\x02\vProvider.V1\xca\x02\vProvider\\V1\xe2\x02\x17Provider\\V1\\GPBMetadata\xea\x02\fProvider::V1b\x06proto3"

var (
	file_provider_v1_provider_proto_rawDescOnce sync.Once
	file_provider_v1_provider_proto_rawDescData []byte
)

func file_provider_v1_provider_proto_rawDescGZIP() []byte {
	file_provider_v1_provider_proto_rawDescOnce.Do(func() {
		file_provider_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)))
	})
	return file_provider_v1_provider_proto_rawDescData
}

var file_provider_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_provider_v1_provider_proto_goTypes = []any{
	(*Provider)(nil),              // 0: provider.v1.Provider
	(*SaveRequest)(nil),           // 1: provider.v1.SaveRequest
	(*SaveResponse)(nil),          // 2: provider.v1.SaveResponse
	(*DeleteRequest)(nil),         // 3: provider.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 4: provider.v1.DeleteResponse
	(*UpdateRequest)(nil),         // 5: provider.v1.UpdateRequest
	(*UpdateResponse)(nil),        // 6: provider.v1.UpdateResponse
	(*ListRequest)(nil),           // 7: provider.v1.ListRequest
	(*ListResponse)(nil),          // 8: provider.v1.ListResponse
	(*FindByIdRequest)(nil),       // 9: provider.v1.FindByIdRequest
	(*FindByIdResponse)(nil),      // 10: provider.v1.FindByIdResponse
	(*FindByChannelRequest)(nil),  // 11: provider.v1.FindByChannelRequest
	(*FindByChannelResponse)(nil), // 12: provider.v1.FindByChannelResponse
	(v1.Channel)(0),               // 13: common.v1.Channel
	(*fieldmaskpb.FieldMask)(nil), // 14: google.protobuf.FieldMask
}
var file_provider_v1_provider_proto_depIdxs = []int32{
	13, // 0: provider.v1.Provider.channel:type_name -> common.v1.Channel
	0,  // 1: provider.v1.SaveRequest.provider:type_name -> provider.v1.Provider
	0,  // 2: provider.v1.SaveResponse.provider:type_name -> provider.v1.Provider
	14, // 3: provider.v1.UpdateRequest.field_mask:type_name -> google.protobuf.FieldMask
	0,  // 4: provider.v1.UpdateRequest.provider:type_name -> provider.v1.Provider
	14, // 5: provider.v1.ListRequest.field_mask:type_name -> google.protobuf.FieldMask
	0,  // 6: provider.v1.ListResponse.providers:type_name -> provider.v1.Provider
	14, // 7: provider.v1.FindByIdRequest.field_mask:type_name -> google.protobuf.FieldMask
	0,  // 8: provider.v1.FindByIdResponse.provider:type_name -> provider.v1.Provider
	14, // 9: provider.v1.FindByChannelRequest.field_mask:type_name -> google.protobuf.FieldMask
	13, // 10: provider.v1.FindByChannelRequest.channel:type_name -> common.v1.Channel
	0,  // 11: provider.v1.FindByChannelResponse.providers:type_name -> provider.v1.Provider
	1,  // 12: provider.v1.ProviderService.Save:input_type -> provider.v1.SaveRequest
	3,  // 13: provider.v1.ProviderService.Delete:input_type -> provider.v1.DeleteRequest
	5,  // 14: provider.v1.ProviderService.Update:input_type -> provider.v1.UpdateRequest
	7,  // 15: provider.v1.ProviderService.List:input_type -> provider.v1.ListRequest
	9,  // 16: provider.v1.ProviderService.FindById:input_type -> provider.v1.FindByIdRequest
	11, // 17: provider.v1.ProviderService.FindByChannel:input_type -> provider.v1.FindByChannelRequest
	2,  // 18: provider.v1.ProviderService.Save:output_type -> provider.v1.SaveResponse
	4,  // 19: provider.v1.ProviderService.Delete:output_type -> provider.v1.DeleteResponse
	6,  // 20: provider.v1.ProviderService.Update:output_type -> provider.v1.UpdateResponse
	8,  // 21: provider.v1.ProviderService.List:output_type -> provider.v1.ListResponse
	10, // 22: provider.v1.ProviderService.FindById:output_type -> provider.v1.FindByIdResponse
	12, // 23: provider.v1.ProviderService.FindByChannel:output_type -> provider.v1.FindByChannelResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_provider_v1_provider_proto_init() }
func file_provider_v1_provider_proto_init() {
	if File_provider_v1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_provider_v1_provider_proto_rawDesc), len(file_provider_v1_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_provider_v1_provider_proto_goTypes,
		DependencyIndexes: file_provider_v1_provider_proto_depIdxs,
		MessageInfos:      file_provider_v1_provider_proto_msgTypes,
	}.Build()
	File_provider_v1_provider_proto = out.File
	file_provider_v1_provider_proto_goTypes = nil
	file_provider_v1_provider_proto_depIdxs = nil
}
