// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: business/v1/business.proto

package businessv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusinessInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BizKey        string                 `protobuf:"bytes,2,opt,name=biz_key,json=bizKey,proto3" json:"biz_key,omitempty"`
	BizName       string                 `protobuf:"bytes,3,opt,name=biz_name,json=bizName,proto3" json:"biz_name,omitempty"`
	BizType       string                 `protobuf:"bytes,4,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	BizSecret     string                 `protobuf:"bytes,5,opt,name=biz_secret,json=bizSecret,proto3" json:"biz_secret,omitempty"`
	Contact       string                 `protobuf:"bytes,6,opt,name=contact,proto3" json:"contact,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,7,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	CreatorId     uint64                 `protobuf:"varint,8,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessInfo) Reset() {
	*x = BusinessInfo{}
	mi := &file_business_v1_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessInfo) ProtoMessage() {}

func (x *BusinessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessInfo.ProtoReflect.Descriptor instead.
func (*BusinessInfo) Descriptor() ([]byte, []int) {
	return file_business_v1_business_proto_rawDescGZIP(), []int{0}
}

func (x *BusinessInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BusinessInfo) GetBizKey() string {
	if x != nil {
		return x.BizKey
	}
	return ""
}

func (x *BusinessInfo) GetBizName() string {
	if x != nil {
		return x.BizName
	}
	return ""
}

func (x *BusinessInfo) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *BusinessInfo) GetBizSecret() string {
	if x != nil {
		return x.BizSecret
	}
	return ""
}

func (x *BusinessInfo) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *BusinessInfo) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *BusinessInfo) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *BusinessInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *BusinessInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type SaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         uint64                 `protobuf:"varint,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	BizKey        string                 `protobuf:"bytes,2,opt,name=biz_key,json=bizKey,proto3" json:"biz_key,omitempty"`
	BizName       string                 `protobuf:"bytes,3,opt,name=biz_name,json=bizName,proto3" json:"biz_name,omitempty"`
	BizType       string                 `protobuf:"bytes,4,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	Contact       string                 `protobuf:"bytes,5,opt,name=contact,proto3" json:"contact,omitempty"`
	ContactEmail  string                 `protobuf:"bytes,6,opt,name=contact_email,json=contactEmail,proto3" json:"contact_email,omitempty"`
	CreatorId     uint64                 `protobuf:"varint,7,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_business_v1_business_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_business_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_business_v1_business_proto_rawDescGZIP(), []int{1}
}

func (x *SaveRequest) GetBizId() uint64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *SaveRequest) GetBizKey() string {
	if x != nil {
		return x.BizKey
	}
	return ""
}

func (x *SaveRequest) GetBizName() string {
	if x != nil {
		return x.BizName
	}
	return ""
}

func (x *SaveRequest) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *SaveRequest) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *SaveRequest) GetContactEmail() string {
	if x != nil {
		return x.ContactEmail
	}
	return ""
}

func (x *SaveRequest) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessInfo  *BusinessInfo          `protobuf:"bytes,1,opt,name=business_info,json=businessInfo,proto3" json:"business_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_business_v1_business_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_business_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_business_v1_business_proto_rawDescGZIP(), []int{2}
}

func (x *SaveResponse) GetBusinessInfo() *BusinessInfo {
	if x != nil {
		return x.BusinessInfo
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BizId         uint64                 `protobuf:"varint,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_business_v1_business_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_business_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_business_v1_business_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetBizId() uint64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_business_v1_business_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_business_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_business_v1_business_proto_rawDescGZIP(), []int{4}
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	BizName       string                 `protobuf:"bytes,3,opt,name=biz_name,json=bizName,proto3" json:"biz_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_business_v1_business_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_business_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_business_v1_business_proto_rawDescGZIP(), []int{5}
}

func (x *SearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetBizName() string {
	if x != nil {
		return x.BizName
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*BusinessInfo        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_business_v1_business_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_business_v1_business_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_business_v1_business_proto_rawDescGZIP(), []int{6}
}

func (x *SearchResponse) GetRecords() []*BusinessInfo {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *SearchResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_business_v1_business_proto protoreflect.FileDescriptor

const file_business_v1_business_proto_rawDesc = "" +
	"\n" +
	"\x1abusiness/v1/business.proto\x12\vbusiness.v1\"\xa8\x02\n" +
	"\fBusinessInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\abiz_key\x18\x02 \x01(\tR\x06bizKey\x12\x19\n" +
	"\bbiz_name\x18\x03 \x01(\tR\abizName\x12\x19\n" +
	"\bbiz_type\x18\x04 \x01(\tR\abizType\x12\x1d\n" +
	"\n" +
	"biz_secret\x18\x05 \x01(\tR\tbizSecret\x12\x18\n" +
	"\acontact\x18\x06 \x01(\tR\acontact\x12#\n" +
	"\rcontact_email\x18\a \x01(\tR\fcontactEmail\x12\x1d\n" +
	"\n" +
	"creator_id\x18\b \x01(\x04R\tcreatorId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\"\xd1\x01\n" +
	"\vSaveRequest\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\x04R\x05bizId\x12\x17\n" +
	"\abiz_key\x18\x02 \x01(\tR\x06bizKey\x12\x19\n" +
	"\bbiz_name\x18\x03 \x01(\tR\abizName\x12\x19\n" +
	"\bbiz_type\x18\x04 \x01(\tR\abizType\x12\x18\n" +
	"\acontact\x18\x05 \x01(\tR\acontact\x12#\n" +
	"\rcontact_email\x18\x06 \x01(\tR\fcontactEmail\x12\x1d\n" +
	"\n" +
	"creator_id\x18\a \x01(\x04R\tcreatorId\"N\n" +
	"\fSaveResponse\x12>\n" +
	"\rbusiness_info\x18\x01 \x01(\v2\x19.business.v1.BusinessInfoR\fbusinessInfo\"&\n" +
	"\rDeleteRequest\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\x04R\x05bizId\"\x10\n" +
	"\x0eDeleteResponse\"X\n" +
	"\rSearchRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x19\n" +
	"\bbiz_name\x18\x03 \x01(\tR\abizName\"[\n" +
	"\x0eSearchResponse\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.business.v1.BusinessInfoR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xd4\x01\n" +
	"\x0fBusinessService\x12;\n" +
	"\x04Save\x12\x18.business.v1.SaveRequest\x1a\x19.business.v1.SaveResponse\x12A\n" +
	"\x06Delete\x12\x1a.business.v1.DeleteRequest\x1a\x1b.business.v1.DeleteResponse\x12A\n" +
	"\x06Search\x12\x1a.business.v1.SearchRequest\x1a\x1b.business.v1.SearchResponseB\xa7\x01\n" +
	"\x0fcom.business.v1B\rBusinessProtoP\x01Z8github.com/JrMarcco/kuryr-api/api/business/v1;businessv1\xa2\x02\x03BXX\xaa\x02\vBusiness.V1\xca\x02\vBusiness\\V1\xe2\x02\x17Business\\V1\\GPBMetadata\xea\x02\fBusiness::V1b\x06proto3"

var (
	file_business_v1_business_proto_rawDescOnce sync.Once
	file_business_v1_business_proto_rawDescData []byte
)

func file_business_v1_business_proto_rawDescGZIP() []byte {
	file_business_v1_business_proto_rawDescOnce.Do(func() {
		file_business_v1_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_business_v1_business_proto_rawDesc), len(file_business_v1_business_proto_rawDesc)))
	})
	return file_business_v1_business_proto_rawDescData
}

var file_business_v1_business_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_business_v1_business_proto_goTypes = []any{
	(*BusinessInfo)(nil),   // 0: business.v1.BusinessInfo
	(*SaveRequest)(nil),    // 1: business.v1.SaveRequest
	(*SaveResponse)(nil),   // 2: business.v1.SaveResponse
	(*DeleteRequest)(nil),  // 3: business.v1.DeleteRequest
	(*DeleteResponse)(nil), // 4: business.v1.DeleteResponse
	(*SearchRequest)(nil),  // 5: business.v1.SearchRequest
	(*SearchResponse)(nil), // 6: business.v1.SearchResponse
}
var file_business_v1_business_proto_depIdxs = []int32{
	0, // 0: business.v1.SaveResponse.business_info:type_name -> business.v1.BusinessInfo
	0, // 1: business.v1.SearchResponse.records:type_name -> business.v1.BusinessInfo
	1, // 2: business.v1.BusinessService.Save:input_type -> business.v1.SaveRequest
	3, // 3: business.v1.BusinessService.Delete:input_type -> business.v1.DeleteRequest
	5, // 4: business.v1.BusinessService.Search:input_type -> business.v1.SearchRequest
	2, // 5: business.v1.BusinessService.Save:output_type -> business.v1.SaveResponse
	4, // 6: business.v1.BusinessService.Delete:output_type -> business.v1.DeleteResponse
	6, // 7: business.v1.BusinessService.Search:output_type -> business.v1.SearchResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_business_v1_business_proto_init() }
func file_business_v1_business_proto_init() {
	if File_business_v1_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_business_v1_business_proto_rawDesc), len(file_business_v1_business_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_business_v1_business_proto_goTypes,
		DependencyIndexes: file_business_v1_business_proto_depIdxs,
		MessageInfos:      file_business_v1_business_proto_msgTypes,
	}.Build()
	File_business_v1_business_proto = out.File
	file_business_v1_business_proto_goTypes = nil
	file_business_v1_business_proto_depIdxs = nil
}
