// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: config/v1/config.proto

package configv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RetryConfig 重试策略配置
type RetryPolicyConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxRetryTimes     int32                  `protobuf:"varint,1,opt,name=max_retry_times,json=maxRetryTimes,proto3" json:"max_retry_times,omitempty"`
	InitIntervalMs    int32                  `protobuf:"varint,2,opt,name=init_interval_ms,json=initIntervalMs,proto3" json:"init_interval_ms,omitempty"`
	MaxIntervalMs     int32                  `protobuf:"varint,3,opt,name=max_interval_ms,json=maxIntervalMs,proto3" json:"max_interval_ms,omitempty"`
	BackoffMultiplier float64                `protobuf:"fixed64,4,opt,name=backoff_multiplier,json=backoffMultiplier,proto3" json:"backoff_multiplier,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RetryPolicyConfig) Reset() {
	*x = RetryPolicyConfig{}
	mi := &file_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicyConfig) ProtoMessage() {}

func (x *RetryPolicyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicyConfig.ProtoReflect.Descriptor instead.
func (*RetryPolicyConfig) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *RetryPolicyConfig) GetMaxRetryTimes() int32 {
	if x != nil {
		return x.MaxRetryTimes
	}
	return 0
}

func (x *RetryPolicyConfig) GetInitIntervalMs() int32 {
	if x != nil {
		return x.InitIntervalMs
	}
	return 0
}

func (x *RetryPolicyConfig) GetMaxIntervalMs() int32 {
	if x != nil {
		return x.MaxIntervalMs
	}
	return 0
}

func (x *RetryPolicyConfig) GetBackoffMultiplier() float64 {
	if x != nil {
		return x.BackoffMultiplier
	}
	return 0
}

// CallbackConfig 回调通知配置
type CallbackConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	RetryPolicy   *RetryPolicyConfig     `protobuf:"bytes,2,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackConfig) Reset() {
	*x = CallbackConfig{}
	mi := &file_config_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackConfig) ProtoMessage() {}

func (x *CallbackConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackConfig.ProtoReflect.Descriptor instead.
func (*CallbackConfig) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *CallbackConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CallbackConfig) GetRetryPolicy() *RetryPolicyConfig {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

// ChannelItem 渠道项
type ChannelItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"` // 优先级
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelItem) Reset() {
	*x = ChannelItem{}
	mi := &file_config_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelItem) ProtoMessage() {}

func (x *ChannelItem) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelItem.ProtoReflect.Descriptor instead.
func (*ChannelItem) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelItem) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ChannelItem) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ChannelItem) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ChannelConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ChannelItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	RetryPolicy   *RetryPolicyConfig     `protobuf:"bytes,2,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelConfig) Reset() {
	*x = ChannelConfig{}
	mi := &file_config_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelConfig) ProtoMessage() {}

func (x *ChannelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelConfig.ProtoReflect.Descriptor instead.
func (*ChannelConfig) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelConfig) GetItems() []*ChannelItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ChannelConfig) GetRetryPolicy() *RetryPolicyConfig {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

type MonthlyQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sms           int32                  `protobuf:"varint,1,opt,name=sms,proto3" json:"sms,omitempty"`
	Email         int32                  `protobuf:"varint,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyQuota) Reset() {
	*x = MonthlyQuota{}
	mi := &file_config_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyQuota) ProtoMessage() {}

func (x *MonthlyQuota) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyQuota.ProtoReflect.Descriptor instead.
func (*MonthlyQuota) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *MonthlyQuota) GetSms() int32 {
	if x != nil {
		return x.Sms
	}
	return 0
}

func (x *MonthlyQuota) GetEmail() int32 {
	if x != nil {
		return x.Email
	}
	return 0
}

type DailyQuota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sms           int32                  `protobuf:"varint,1,opt,name=sms,proto3" json:"sms,omitempty"`
	Email         int32                  `protobuf:"varint,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyQuota) Reset() {
	*x = DailyQuota{}
	mi := &file_config_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyQuota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyQuota) ProtoMessage() {}

func (x *DailyQuota) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyQuota.ProtoReflect.Descriptor instead.
func (*DailyQuota) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *DailyQuota) GetSms() int32 {
	if x != nil {
		return x.Sms
	}
	return 0
}

func (x *DailyQuota) GetEmail() int32 {
	if x != nil {
		return x.Email
	}
	return 0
}

type QuotaConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monthly       *MonthlyQuota          `protobuf:"bytes,1,opt,name=monthly,proto3" json:"monthly,omitempty"`
	Daily         *DailyQuota            `protobuf:"bytes,2,opt,name=daily,proto3" json:"daily,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaConfig) Reset() {
	*x = QuotaConfig{}
	mi := &file_config_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaConfig) ProtoMessage() {}

func (x *QuotaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaConfig.ProtoReflect.Descriptor instead.
func (*QuotaConfig) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *QuotaConfig) GetMonthly() *MonthlyQuota {
	if x != nil {
		return x.Monthly
	}
	return nil
}

func (x *QuotaConfig) GetDaily() *DailyQuota {
	if x != nil {
		return x.Daily
	}
	return nil
}

// BizConfig 业务方配置
type BizConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OwnerId        uint64                 `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"` // 对应 biz_info 表的 id
	ChannelConfig  *ChannelConfig         `protobuf:"bytes,2,opt,name=channel_config,json=channelConfig,proto3" json:"channel_config,omitempty"`
	Quota          *QuotaConfig           `protobuf:"bytes,3,opt,name=quota,proto3" json:"quota,omitempty"`
	CallbackConfig *CallbackConfig        `protobuf:"bytes,4,opt,name=callback_config,json=callbackConfig,proto3" json:"callback_config,omitempty"`
	RateLimit      int32                  `protobuf:"varint,5,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BizConfig) Reset() {
	*x = BizConfig{}
	mi := &file_config_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BizConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BizConfig) ProtoMessage() {}

func (x *BizConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BizConfig.ProtoReflect.Descriptor instead.
func (*BizConfig) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *BizConfig) GetOwnerId() uint64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *BizConfig) GetChannelConfig() *ChannelConfig {
	if x != nil {
		return x.ChannelConfig
	}
	return nil
}

func (x *BizConfig) GetQuota() *QuotaConfig {
	if x != nil {
		return x.Quota
	}
	return nil
}

func (x *BizConfig) GetCallbackConfig() *CallbackConfig {
	if x != nil {
		return x.CallbackConfig
	}
	return nil
}

func (x *BizConfig) GetRateLimit() int32 {
	if x != nil {
		return x.RateLimit
	}
	return 0
}

type SaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *BizConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_config_v1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{8}
}

func (x *SaveRequest) GetConfig() *BizConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_config_v1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{9}
}

func (x *SaveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SaveResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_config_v1_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_config_v1_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdRequest) Reset() {
	*x = GetByIdRequest{}
	mi := &file_config_v1_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdRequest) ProtoMessage() {}

func (x *GetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdRequest.ProtoReflect.Descriptor instead.
func (*GetByIdRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{12}
}

func (x *GetByIdRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *BizConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdResponse) Reset() {
	*x = GetByIdResponse{}
	mi := &file_config_v1_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdResponse) ProtoMessage() {}

func (x *GetByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdResponse.ProtoReflect.Descriptor instead.
func (*GetByIdResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{13}
}

func (x *GetByIdResponse) GetConfig() *BizConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type GetByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdsRequest) Reset() {
	*x = GetByIdsRequest{}
	mi := &file_config_v1_config_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdsRequest) ProtoMessage() {}

func (x *GetByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetByIdsRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{14}
}

func (x *GetByIdsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       map[uint64]*BizConfig  `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdsResponse) Reset() {
	*x = GetByIdsResponse{}
	mi := &file_config_v1_config_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdsResponse) ProtoMessage() {}

func (x *GetByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetByIdsResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{15}
}

func (x *GetByIdsResponse) GetConfigs() map[uint64]*BizConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

var File_config_v1_config_proto protoreflect.FileDescriptor

const file_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x16config/v1/config.proto\x12\tconfig.v1\"\xbc\x01\n" +
	"\x11RetryPolicyConfig\x12&\n" +
	"\x0fmax_retry_times\x18\x01 \x01(\x05R\rmaxRetryTimes\x12(\n" +
	"\x10init_interval_ms\x18\x02 \x01(\x05R\x0einitIntervalMs\x12&\n" +
	"\x0fmax_interval_ms\x18\x03 \x01(\x05R\rmaxIntervalMs\x12-\n" +
	"\x12backoff_multiplier\x18\x04 \x01(\x01R\x11backoffMultiplier\"t\n" +
	"\x0eCallbackConfig\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12?\n" +
	"\fretry_policy\x18\x02 \x01(\v2\x1c.config.v1.RetryPolicyConfigR\vretryPolicy\"]\n" +
	"\vChannelItem\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"~\n" +
	"\rChannelConfig\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.config.v1.ChannelItemR\x05items\x12?\n" +
	"\fretry_policy\x18\x02 \x01(\v2\x1c.config.v1.RetryPolicyConfigR\vretryPolicy\"6\n" +
	"\fMonthlyQuota\x12\x10\n" +
	"\x03sms\x18\x01 \x01(\x05R\x03sms\x12\x14\n" +
	"\x05email\x18\x02 \x01(\x05R\x05email\"4\n" +
	"\n" +
	"DailyQuota\x12\x10\n" +
	"\x03sms\x18\x01 \x01(\x05R\x03sms\x12\x14\n" +
	"\x05email\x18\x02 \x01(\x05R\x05email\"m\n" +
	"\vQuotaConfig\x121\n" +
	"\amonthly\x18\x01 \x01(\v2\x17.config.v1.MonthlyQuotaR\amonthly\x12+\n" +
	"\x05daily\x18\x02 \x01(\v2\x15.config.v1.DailyQuotaR\x05daily\"\xf8\x01\n" +
	"\tBizConfig\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x04R\aownerId\x12?\n" +
	"\x0echannel_config\x18\x02 \x01(\v2\x18.config.v1.ChannelConfigR\rchannelConfig\x12,\n" +
	"\x05quota\x18\x03 \x01(\v2\x16.config.v1.QuotaConfigR\x05quota\x12B\n" +
	"\x0fcallback_config\x18\x04 \x01(\v2\x19.config.v1.CallbackConfigR\x0ecallbackConfig\x12\x1d\n" +
	"\n" +
	"rate_limit\x18\x05 \x01(\x05R\trateLimit\";\n" +
	"\vSaveRequest\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x14.config.v1.BizConfigR\x06config\"J\n" +
	"\fSaveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"<\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\" \n" +
	"\x0eGetByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"?\n" +
	"\x0fGetByIdResponse\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x14.config.v1.BizConfigR\x06config\"#\n" +
	"\x0fGetByIdsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x04R\x03ids\"\xa8\x01\n" +
	"\x10GetByIdsResponse\x12B\n" +
	"\aconfigs\x18\x01 \x03(\v2(.config.v1.GetByIdsResponse.ConfigsEntryR\aconfigs\x1aP\n" +
	"\fConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.config.v1.BizConfigR\x05value:\x028\x012\x91\x02\n" +
	"\x10BizConfigService\x127\n" +
	"\x04Save\x12\x16.config.v1.SaveRequest\x1a\x17.config.v1.SaveResponse\x12=\n" +
	"\x06Delete\x12\x18.config.v1.DeleteRequest\x1a\x19.config.v1.DeleteResponse\x12@\n" +
	"\aGetById\x12\x19.config.v1.GetByIdRequest\x1a\x1a.config.v1.GetByIdResponse\x12C\n" +
	"\bGetByIds\x12\x1a.config.v1.GetByIdsRequest\x1a\x1b.config.v1.GetByIdsResponseB\x97\x01\n" +
	"\rcom.config.v1B\vConfigProtoP\x01Z4github.com/JrMarcco/kuryr-api/api/config/v1;configv1\xa2\x02\x03CXX\xaa\x02\tConfig.V1\xca\x02\tConfig\\V1\xe2\x02\x15Config\\V1\\GPBMetadata\xea\x02\n" +
	"Config::V1b\x06proto3"

var (
	file_config_v1_config_proto_rawDescOnce sync.Once
	file_config_v1_config_proto_rawDescData []byte
)

func file_config_v1_config_proto_rawDescGZIP() []byte {
	file_config_v1_config_proto_rawDescOnce.Do(func() {
		file_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)))
	})
	return file_config_v1_config_proto_rawDescData
}

var file_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_config_v1_config_proto_goTypes = []any{
	(*RetryPolicyConfig)(nil), // 0: config.v1.RetryPolicyConfig
	(*CallbackConfig)(nil),    // 1: config.v1.CallbackConfig
	(*ChannelItem)(nil),       // 2: config.v1.ChannelItem
	(*ChannelConfig)(nil),     // 3: config.v1.ChannelConfig
	(*MonthlyQuota)(nil),      // 4: config.v1.MonthlyQuota
	(*DailyQuota)(nil),        // 5: config.v1.DailyQuota
	(*QuotaConfig)(nil),       // 6: config.v1.QuotaConfig
	(*BizConfig)(nil),         // 7: config.v1.BizConfig
	(*SaveRequest)(nil),       // 8: config.v1.SaveRequest
	(*SaveResponse)(nil),      // 9: config.v1.SaveResponse
	(*DeleteRequest)(nil),     // 10: config.v1.DeleteRequest
	(*DeleteResponse)(nil),    // 11: config.v1.DeleteResponse
	(*GetByIdRequest)(nil),    // 12: config.v1.GetByIdRequest
	(*GetByIdResponse)(nil),   // 13: config.v1.GetByIdResponse
	(*GetByIdsRequest)(nil),   // 14: config.v1.GetByIdsRequest
	(*GetByIdsResponse)(nil),  // 15: config.v1.GetByIdsResponse
	nil,                       // 16: config.v1.GetByIdsResponse.ConfigsEntry
}
var file_config_v1_config_proto_depIdxs = []int32{
	0,  // 0: config.v1.CallbackConfig.retry_policy:type_name -> config.v1.RetryPolicyConfig
	2,  // 1: config.v1.ChannelConfig.items:type_name -> config.v1.ChannelItem
	0,  // 2: config.v1.ChannelConfig.retry_policy:type_name -> config.v1.RetryPolicyConfig
	4,  // 3: config.v1.QuotaConfig.monthly:type_name -> config.v1.MonthlyQuota
	5,  // 4: config.v1.QuotaConfig.daily:type_name -> config.v1.DailyQuota
	3,  // 5: config.v1.BizConfig.channel_config:type_name -> config.v1.ChannelConfig
	6,  // 6: config.v1.BizConfig.quota:type_name -> config.v1.QuotaConfig
	1,  // 7: config.v1.BizConfig.callback_config:type_name -> config.v1.CallbackConfig
	7,  // 8: config.v1.SaveRequest.config:type_name -> config.v1.BizConfig
	7,  // 9: config.v1.GetByIdResponse.config:type_name -> config.v1.BizConfig
	16, // 10: config.v1.GetByIdsResponse.configs:type_name -> config.v1.GetByIdsResponse.ConfigsEntry
	7,  // 11: config.v1.GetByIdsResponse.ConfigsEntry.value:type_name -> config.v1.BizConfig
	8,  // 12: config.v1.BizConfigService.Save:input_type -> config.v1.SaveRequest
	10, // 13: config.v1.BizConfigService.Delete:input_type -> config.v1.DeleteRequest
	12, // 14: config.v1.BizConfigService.GetById:input_type -> config.v1.GetByIdRequest
	14, // 15: config.v1.BizConfigService.GetByIds:input_type -> config.v1.GetByIdsRequest
	9,  // 16: config.v1.BizConfigService.Save:output_type -> config.v1.SaveResponse
	11, // 17: config.v1.BizConfigService.Delete:output_type -> config.v1.DeleteResponse
	13, // 18: config.v1.BizConfigService.GetById:output_type -> config.v1.GetByIdResponse
	15, // 19: config.v1.BizConfigService.GetByIds:output_type -> config.v1.GetByIdsResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_config_v1_config_proto_init() }
func file_config_v1_config_proto_init() {
	if File_config_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_v1_config_proto_goTypes,
		DependencyIndexes: file_config_v1_config_proto_depIdxs,
		MessageInfos:      file_config_v1_config_proto_msgTypes,
	}.Build()
	File_config_v1_config_proto = out.File
	file_config_v1_config_proto_goTypes = nil
	file_config_v1_config_proto_depIdxs = nil
}
