// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: config/v1/config.proto

package configv1

import (
	v1 "github.com/JrMarcco/kuryr-api/api/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RetryConfig 重试策略配置
type RetryPolicyConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxRetryTimes  int32                  `protobuf:"varint,1,opt,name=max_retry_times,json=maxRetryTimes,proto3" json:"max_retry_times,omitempty"`
	InitIntervalMs int32                  `protobuf:"varint,2,opt,name=init_interval_ms,json=initIntervalMs,proto3" json:"init_interval_ms,omitempty"`
	MaxIntervalMs  int32                  `protobuf:"varint,3,opt,name=max_interval_ms,json=maxIntervalMs,proto3" json:"max_interval_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetryPolicyConfig) Reset() {
	*x = RetryPolicyConfig{}
	mi := &file_config_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicyConfig) ProtoMessage() {}

func (x *RetryPolicyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicyConfig.ProtoReflect.Descriptor instead.
func (*RetryPolicyConfig) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *RetryPolicyConfig) GetMaxRetryTimes() int32 {
	if x != nil {
		return x.MaxRetryTimes
	}
	return 0
}

func (x *RetryPolicyConfig) GetInitIntervalMs() int32 {
	if x != nil {
		return x.InitIntervalMs
	}
	return 0
}

func (x *RetryPolicyConfig) GetMaxIntervalMs() int32 {
	if x != nil {
		return x.MaxIntervalMs
	}
	return 0
}

// CallbackConfig 回调通知配置
type CallbackConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	RetryPolicy   *RetryPolicyConfig     `protobuf:"bytes,2,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackConfig) Reset() {
	*x = CallbackConfig{}
	mi := &file_config_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackConfig) ProtoMessage() {}

func (x *CallbackConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackConfig.ProtoReflect.Descriptor instead.
func (*CallbackConfig) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *CallbackConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CallbackConfig) GetRetryPolicy() *RetryPolicyConfig {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

// ChannelItem 渠道项
type ChannelItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       v1.Channel             `protobuf:"varint,1,opt,name=channel,proto3,enum=common.v1.Channel" json:"channel,omitempty"`
	Priority      int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"` // 优先级
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelItem) Reset() {
	*x = ChannelItem{}
	mi := &file_config_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelItem) ProtoMessage() {}

func (x *ChannelItem) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelItem.ProtoReflect.Descriptor instead.
func (*ChannelItem) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *ChannelItem) GetChannel() v1.Channel {
	if x != nil {
		return x.Channel
	}
	return v1.Channel(0)
}

func (x *ChannelItem) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ChannelItem) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ChannelConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ChannelItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	RetryPolicy   *RetryPolicyConfig     `protobuf:"bytes,2,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelConfig) Reset() {
	*x = ChannelConfig{}
	mi := &file_config_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelConfig) ProtoMessage() {}

func (x *ChannelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelConfig.ProtoReflect.Descriptor instead.
func (*ChannelConfig) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *ChannelConfig) GetItems() []*ChannelItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ChannelConfig) GetRetryPolicy() *RetryPolicyConfig {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

type Quota struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sms           int32                  `protobuf:"varint,1,opt,name=sms,proto3" json:"sms,omitempty"`
	Email         int32                  `protobuf:"varint,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quota) Reset() {
	*x = Quota{}
	mi := &file_config_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quota) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quota) ProtoMessage() {}

func (x *Quota) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quota.ProtoReflect.Descriptor instead.
func (*Quota) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *Quota) GetSms() int32 {
	if x != nil {
		return x.Sms
	}
	return 0
}

func (x *Quota) GetEmail() int32 {
	if x != nil {
		return x.Email
	}
	return 0
}

type QuotaConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Monthly       *Quota                 `protobuf:"bytes,1,opt,name=monthly,proto3" json:"monthly,omitempty"`
	Daily         *Quota                 `protobuf:"bytes,2,opt,name=daily,proto3" json:"daily,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaConfig) Reset() {
	*x = QuotaConfig{}
	mi := &file_config_v1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaConfig) ProtoMessage() {}

func (x *QuotaConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaConfig.ProtoReflect.Descriptor instead.
func (*QuotaConfig) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{5}
}

func (x *QuotaConfig) GetMonthly() *Quota {
	if x != nil {
		return x.Monthly
	}
	return nil
}

func (x *QuotaConfig) GetDaily() *Quota {
	if x != nil {
		return x.Daily
	}
	return nil
}

// BizConfig 业务方配置
type BizConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BizId          uint64                 `protobuf:"varint,2,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	OwnerType      string                 `protobuf:"bytes,3,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	ChannelConfig  *ChannelConfig         `protobuf:"bytes,4,opt,name=channel_config,json=channelConfig,proto3" json:"channel_config,omitempty"`
	QuotaConfig    *QuotaConfig           `protobuf:"bytes,5,opt,name=quota_config,json=quotaConfig,proto3" json:"quota_config,omitempty"`
	CallbackConfig *CallbackConfig        `protobuf:"bytes,6,opt,name=callback_config,json=callbackConfig,proto3" json:"callback_config,omitempty"`
	RateLimit      int32                  `protobuf:"varint,7,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BizConfig) Reset() {
	*x = BizConfig{}
	mi := &file_config_v1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BizConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BizConfig) ProtoMessage() {}

func (x *BizConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BizConfig.ProtoReflect.Descriptor instead.
func (*BizConfig) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{6}
}

func (x *BizConfig) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BizConfig) GetBizId() uint64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *BizConfig) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

func (x *BizConfig) GetChannelConfig() *ChannelConfig {
	if x != nil {
		return x.ChannelConfig
	}
	return nil
}

func (x *BizConfig) GetQuotaConfig() *QuotaConfig {
	if x != nil {
		return x.QuotaConfig
	}
	return nil
}

func (x *BizConfig) GetCallbackConfig() *CallbackConfig {
	if x != nil {
		return x.CallbackConfig
	}
	return nil
}

func (x *BizConfig) GetRateLimit() int32 {
	if x != nil {
		return x.RateLimit
	}
	return 0
}

type SaveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BizId          uint64                 `protobuf:"varint,1,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
	ChannelConfig  *ChannelConfig         `protobuf:"bytes,2,opt,name=channel_config,json=channelConfig,proto3" json:"channel_config,omitempty"`
	QuotaConfig    *QuotaConfig           `protobuf:"bytes,3,opt,name=quota_config,json=quotaConfig,proto3" json:"quota_config,omitempty"`
	CallbackConfig *CallbackConfig        `protobuf:"bytes,4,opt,name=callback_config,json=callbackConfig,proto3" json:"callback_config,omitempty"`
	RateLimit      int32                  `protobuf:"varint,5,opt,name=rate_limit,json=rateLimit,proto3" json:"rate_limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SaveRequest) Reset() {
	*x = SaveRequest{}
	mi := &file_config_v1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRequest) ProtoMessage() {}

func (x *SaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRequest.ProtoReflect.Descriptor instead.
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{7}
}

func (x *SaveRequest) GetBizId() uint64 {
	if x != nil {
		return x.BizId
	}
	return 0
}

func (x *SaveRequest) GetChannelConfig() *ChannelConfig {
	if x != nil {
		return x.ChannelConfig
	}
	return nil
}

func (x *SaveRequest) GetQuotaConfig() *QuotaConfig {
	if x != nil {
		return x.QuotaConfig
	}
	return nil
}

func (x *SaveRequest) GetCallbackConfig() *CallbackConfig {
	if x != nil {
		return x.CallbackConfig
	}
	return nil
}

func (x *SaveRequest) GetRateLimit() int32 {
	if x != nil {
		return x.RateLimit
	}
	return 0
}

type SaveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	BizConfig     *BizConfig             `protobuf:"bytes,2,opt,name=biz_config,json=bizConfig,proto3" json:"biz_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveResponse) Reset() {
	*x = SaveResponse{}
	mi := &file_config_v1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveResponse) ProtoMessage() {}

func (x *SaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveResponse.ProtoReflect.Descriptor instead.
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{8}
}

func (x *SaveResponse) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *SaveResponse) GetBizConfig() *BizConfig {
	if x != nil {
		return x.BizConfig
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_config_v1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_config_v1_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{10}
}

type FindByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldMask     *fieldmaskpb.FieldMask `protobuf:"bytes,1,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdRequest) Reset() {
	*x = FindByIdRequest{}
	mi := &file_config_v1_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdRequest) ProtoMessage() {}

func (x *FindByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdRequest.ProtoReflect.Descriptor instead.
func (*FindByIdRequest) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{11}
}

func (x *FindByIdRequest) GetFieldMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *FindByIdRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *BizConfig             `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdResponse) Reset() {
	*x = FindByIdResponse{}
	mi := &file_config_v1_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdResponse) ProtoMessage() {}

func (x *FindByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdResponse.ProtoReflect.Descriptor instead.
func (*FindByIdResponse) Descriptor() ([]byte, []int) {
	return file_config_v1_config_proto_rawDescGZIP(), []int{12}
}

func (x *FindByIdResponse) GetConfig() *BizConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_config_v1_config_proto protoreflect.FileDescriptor

const file_config_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x16config/v1/config.proto\x12\tconfig.v1\x1a\x15common/v1/types.proto\x1a google/protobuf/field_mask.proto\"\x8d\x01\n" +
	"\x11RetryPolicyConfig\x12&\n" +
	"\x0fmax_retry_times\x18\x01 \x01(\x05R\rmaxRetryTimes\x12(\n" +
	"\x10init_interval_ms\x18\x02 \x01(\x05R\x0einitIntervalMs\x12&\n" +
	"\x0fmax_interval_ms\x18\x03 \x01(\x05R\rmaxIntervalMs\"t\n" +
	"\x0eCallbackConfig\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12?\n" +
	"\fretry_policy\x18\x02 \x01(\v2\x1c.config.v1.RetryPolicyConfigR\vretryPolicy\"q\n" +
	"\vChannelItem\x12,\n" +
	"\achannel\x18\x01 \x01(\x0e2\x12.common.v1.ChannelR\achannel\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"~\n" +
	"\rChannelConfig\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.config.v1.ChannelItemR\x05items\x12?\n" +
	"\fretry_policy\x18\x02 \x01(\v2\x1c.config.v1.RetryPolicyConfigR\vretryPolicy\"/\n" +
	"\x05Quota\x12\x10\n" +
	"\x03sms\x18\x01 \x01(\x05R\x03sms\x12\x14\n" +
	"\x05email\x18\x02 \x01(\x05R\x05email\"a\n" +
	"\vQuotaConfig\x12*\n" +
	"\amonthly\x18\x01 \x01(\v2\x10.config.v1.QuotaR\amonthly\x12&\n" +
	"\x05daily\x18\x02 \x01(\v2\x10.config.v1.QuotaR\x05daily\"\xb0\x02\n" +
	"\tBizConfig\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x15\n" +
	"\x06biz_id\x18\x02 \x01(\x04R\x05bizId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\x03 \x01(\tR\townerType\x12?\n" +
	"\x0echannel_config\x18\x04 \x01(\v2\x18.config.v1.ChannelConfigR\rchannelConfig\x129\n" +
	"\fquota_config\x18\x05 \x01(\v2\x16.config.v1.QuotaConfigR\vquotaConfig\x12B\n" +
	"\x0fcallback_config\x18\x06 \x01(\v2\x19.config.v1.CallbackConfigR\x0ecallbackConfig\x12\x1d\n" +
	"\n" +
	"rate_limit\x18\a \x01(\x05R\trateLimit\"\x83\x02\n" +
	"\vSaveRequest\x12\x15\n" +
	"\x06biz_id\x18\x01 \x01(\x04R\x05bizId\x12?\n" +
	"\x0echannel_config\x18\x02 \x01(\v2\x18.config.v1.ChannelConfigR\rchannelConfig\x129\n" +
	"\fquota_config\x18\x03 \x01(\v2\x16.config.v1.QuotaConfigR\vquotaConfig\x12B\n" +
	"\x0fcallback_config\x18\x04 \x01(\v2\x19.config.v1.CallbackConfigR\x0ecallbackConfig\x12\x1d\n" +
	"\n" +
	"rate_limit\x18\x05 \x01(\x05R\trateLimit\"~\n" +
	"\fSaveResponse\x129\n" +
	"\n" +
	"field_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x123\n" +
	"\n" +
	"biz_config\x18\x02 \x01(\v2\x14.config.v1.BizConfigR\tbizConfig\"\x1f\n" +
	"\rDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x10\n" +
	"\x0eDeleteResponse\"\\\n" +
	"\x0fFindByIdRequest\x129\n" +
	"\n" +
	"field_mask\x18\x01 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\"@\n" +
	"\x10FindByIdResponse\x12,\n" +
	"\x06config\x18\x01 \x01(\v2\x14.config.v1.BizConfigR\x06config2\xcf\x01\n" +
	"\x10BizConfigService\x127\n" +
	"\x04Save\x12\x16.config.v1.SaveRequest\x1a\x17.config.v1.SaveResponse\x12=\n" +
	"\x06Delete\x12\x18.config.v1.DeleteRequest\x1a\x19.config.v1.DeleteResponse\x12C\n" +
	"\bFindById\x12\x1a.config.v1.FindByIdRequest\x1a\x1b.config.v1.FindByIdResponseB\x9a\x01\n" +
	"\rcom.config.v1B\vConfigProtoP\x01Z7github.com/JrMarcco/kuryr-api/api/go/config/v1;configv1\xa2\x02\x03CXX\xaa\x02\tConfig.V1\xca\x02\tConfig\\V1\xe2\x02\x15Config\\V1\\GPBMetadata\xea\x02\n" +
	"Config::V1b\x06proto3"

var (
	file_config_v1_config_proto_rawDescOnce sync.Once
	file_config_v1_config_proto_rawDescData []byte
)

func file_config_v1_config_proto_rawDescGZIP() []byte {
	file_config_v1_config_proto_rawDescOnce.Do(func() {
		file_config_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)))
	})
	return file_config_v1_config_proto_rawDescData
}

var file_config_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_config_v1_config_proto_goTypes = []any{
	(*RetryPolicyConfig)(nil),     // 0: config.v1.RetryPolicyConfig
	(*CallbackConfig)(nil),        // 1: config.v1.CallbackConfig
	(*ChannelItem)(nil),           // 2: config.v1.ChannelItem
	(*ChannelConfig)(nil),         // 3: config.v1.ChannelConfig
	(*Quota)(nil),                 // 4: config.v1.Quota
	(*QuotaConfig)(nil),           // 5: config.v1.QuotaConfig
	(*BizConfig)(nil),             // 6: config.v1.BizConfig
	(*SaveRequest)(nil),           // 7: config.v1.SaveRequest
	(*SaveResponse)(nil),          // 8: config.v1.SaveResponse
	(*DeleteRequest)(nil),         // 9: config.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 10: config.v1.DeleteResponse
	(*FindByIdRequest)(nil),       // 11: config.v1.FindByIdRequest
	(*FindByIdResponse)(nil),      // 12: config.v1.FindByIdResponse
	(v1.Channel)(0),               // 13: common.v1.Channel
	(*fieldmaskpb.FieldMask)(nil), // 14: google.protobuf.FieldMask
}
var file_config_v1_config_proto_depIdxs = []int32{
	0,  // 0: config.v1.CallbackConfig.retry_policy:type_name -> config.v1.RetryPolicyConfig
	13, // 1: config.v1.ChannelItem.channel:type_name -> common.v1.Channel
	2,  // 2: config.v1.ChannelConfig.items:type_name -> config.v1.ChannelItem
	0,  // 3: config.v1.ChannelConfig.retry_policy:type_name -> config.v1.RetryPolicyConfig
	4,  // 4: config.v1.QuotaConfig.monthly:type_name -> config.v1.Quota
	4,  // 5: config.v1.QuotaConfig.daily:type_name -> config.v1.Quota
	3,  // 6: config.v1.BizConfig.channel_config:type_name -> config.v1.ChannelConfig
	5,  // 7: config.v1.BizConfig.quota_config:type_name -> config.v1.QuotaConfig
	1,  // 8: config.v1.BizConfig.callback_config:type_name -> config.v1.CallbackConfig
	3,  // 9: config.v1.SaveRequest.channel_config:type_name -> config.v1.ChannelConfig
	5,  // 10: config.v1.SaveRequest.quota_config:type_name -> config.v1.QuotaConfig
	1,  // 11: config.v1.SaveRequest.callback_config:type_name -> config.v1.CallbackConfig
	14, // 12: config.v1.SaveResponse.field_mask:type_name -> google.protobuf.FieldMask
	6,  // 13: config.v1.SaveResponse.biz_config:type_name -> config.v1.BizConfig
	14, // 14: config.v1.FindByIdRequest.field_mask:type_name -> google.protobuf.FieldMask
	6,  // 15: config.v1.FindByIdResponse.config:type_name -> config.v1.BizConfig
	7,  // 16: config.v1.BizConfigService.Save:input_type -> config.v1.SaveRequest
	9,  // 17: config.v1.BizConfigService.Delete:input_type -> config.v1.DeleteRequest
	11, // 18: config.v1.BizConfigService.FindById:input_type -> config.v1.FindByIdRequest
	8,  // 19: config.v1.BizConfigService.Save:output_type -> config.v1.SaveResponse
	10, // 20: config.v1.BizConfigService.Delete:output_type -> config.v1.DeleteResponse
	12, // 21: config.v1.BizConfigService.FindById:output_type -> config.v1.FindByIdResponse
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_config_v1_config_proto_init() }
func file_config_v1_config_proto_init() {
	if File_config_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_config_proto_rawDesc), len(file_config_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_v1_config_proto_goTypes,
		DependencyIndexes: file_config_v1_config_proto_depIdxs,
		MessageInfos:      file_config_v1_config_proto_msgTypes,
	}.Build()
	File_config_v1_config_proto = out.File
	file_config_v1_config_proto_goTypes = nil
	file_config_v1_config_proto_depIdxs = nil
}
